# imports

In [1]:
# !git clone https://github.com/moryacho/street-pattern-classifier.git

# !pip install huggingface_hub geopandas osmnx
# !pip install torch_geometric
# !pip install "folium>=0.12" matplotlib mapclassify

# !pip uninstall torch torchvision torchaudio -y
# !pip cache purge
# !pip install torch torchvision torchaudio

import torch

In [2]:
import geopandas as gpd
import numpy as np
import osmnx as ox
import pandas as pd
import time
from tqdm import tqdm
import os
import networkx as nx
import json

import matplotlib.pyplot as plt
from collections import Counter
from scipy import stats
import warnings

from shapely.geometry import LineString, Polygon, Point
import shapely
import pickle
import ast

# cities

## names

In [10]:
osm_city_names = [
    # East Asia
    "Beijing, China",
    "Chengdu, China",
    "Chongqing, China",
    "Guangzhou, China",
    "Hangzhou, China",
    "Shanghai, China",
    "Shenzhen, China",
    "Wuhan, China",
    "Nanjing, China",
    "Taipei, Taiwan",
    # "Tokyo, Japan", # multyoplygon: so buffer in the ocean
    "Osaka, Japan",
    "Seoul, South Korea",
    
    # South Asia
    "Bangkok, Thailand",
    "Delhi, India",
    "Singapore, Singapore",
    "Kuala Lumpur, Malaysia",
    # "Mumbai, India",
    "Hyderabad, India",
    "Kathmandu, Nepal",
    
    # Oceania
    "Melbourne, Australia",
    "Sydney, Australia",
    "Auckland, New Zealand",
    "Brisbane, Australia",
    
    # Africa
    "Cairo, Egypt",
    "Casablanca, Morocco",
    "Lagos, Nigeria",
    "Nairobi, Kenya",
    # "Johannesburg, South Africa",
    
    # Europe
    "Amsterdam, Netherlands",
    "Brussels, Belgium",
    "London, United Kingdom",
    "Paris, France",
    "Berlin, Germany",
    "Munich, Germany",
    "Madrid, Spain",
    "Milan, Italy",
    "Moscow, Russia",
    "Stockholm, Sweden",
    "Bucharest, Romania",
    "Saint Petersburg, Russia",
    
    # North America
    "New York City, USA",  # Важно: именно "New York City", а не просто "New York"
    "Los Angeles, USA",
    "Detroit, USA",
    "Philadelphia, USA",
    "San Antonio, USA",
    "San Diego, USA",
    "Toronto, Canada",
    "Montreal, Canada",
    "Chicago, USA",
    "Houston, USA",
    "Phoenix, USA",
    
    # South America
    "Lima, Peru",
    "Bogota, Colombia",
    "Sao Paulo, Brazil",  # Можно также "São Paulo, Brazil"
    "Caracas, Venezuela",
    "Brasilia, Brazil",    # Можно также "Brasília, Brazil"
    "Asuncion, Paraguay"
]

## centroids and buffers

In [11]:
BUFFER = 20000
data = []

for city in tqdm(osm_city_names):
    gdf = ox.geocode_to_gdf(city)
    if gdf.crs != 4326:
        print(f"Исходная CRS: {gdf.crs}")
    gdf_projected = gdf.to_crs(gdf.estimate_utm_crs())
    center_point_projected = gdf_projected.centroid.iloc[0]
    
    point_gdf_utm = gpd.GeoDataFrame(geometry=[center_point_projected], crs=gdf_projected.crs)
    buffer_utm = point_gdf_utm.buffer(BUFFER)
    buffer_geo = buffer_utm.to_crs(gdf.crs)    
    center_point_geo = gpd.GeoDataFrame(geometry=[center_point_projected], crs=gdf_projected.crs).to_crs(gdf.crs).geometry.iloc[0]
    
    data.append({
        "city_name": city,
        "centroid": center_point_geo,
        "geometry": buffer_geo.geometry.iloc[0]
    })

  0%|          | 0/55 [00:00<?, ?it/s]

100%|██████████| 55/55 [00:05<00:00, 10.91it/s]

In [12]:
gdf_centroids_polygons = gpd.GeoDataFrame(data, crs='EPSG:4326', geometry='geometry')

In [13]:
# gdf_only_centroids = gpd.GeoDataFrame(data, crs='EPSG:4326', geometry='centroid')

In [14]:
gdf_centroids_polygons.explore()

## drive graph data

In [15]:
# Source - https://stackoverflow.com/a/77965352
# Posted by Nick ODell
# Retrieved 2026-03-19, License - CC BY-SA 4.0

import osmnx as ox

# Must be an overpass instance which supports attic
ox.settings.overpass_endpoint = "https://overpass-api.de/api"

def query_year(coordinate, year):
    date = f'{year}-01-01T00:00:00Z'
    # Request attic data
    ox.settings.overpass_settings = '[out:json][timeout:{timeout}][date:"' + date + '"]{maxsize}'
    graph = ox.graph.graph_from_polygon(coordinate)
    # Restore old settings
    ox.settings.overpass_settings = '[out:json][timeout:{timeout}]{maxsize}'
    return graph

In [ ]:
# gdf_centroids_polygons['graph_2026'] = None
# gdf_centroids_polygons['graph_2020'] = None


for i in tqdm(range(len(gdf_centroids_polygons))):
    row = gdf_centroids_polygons.iloc[i]
    polygon = row['geometry']
    if gdf_centroids_polygons.at[row.name, 'graph_2026']:
        print(f"place {row.city_name} already downloaded")
        continue
    try:
        drive_graph_2026 = ox.graph_from_polygon(polygon, network_type='drive')
        drive_graph_2020 = query_year(polygon, 2020)
        
        gdf_centroids_polygons.at[row.name, 'graph_2026'] = drive_graph_2026
        gdf_centroids_polygons.at[row.name, 'graph_2020'] = drive_graph_2020
    except Exception  as e:
        print(f"place: {row.city_name} error: {e}")

    if i % 10 == 0:
        gdf_centroids_polygons.to_pickle(f"graphs_through_years//gdf_{i // 10}.pkl")

gdf_centroids_polygons.to_pickle(f"graphs_through_years//gdf_final.pkl")

 73%|███████▎  | 40/55 [3:57:06<1:28:55, 355.67s/it]

MemoryError:

In [3]:
# gdf_centroids_polygons.to_pickle("gdf_56_cities_centroids_polygons_graphs.pkl")
gdf_centroids_polygons = gpd.GeoDataFrame(pd.read_pickle("graphs_through_years//gdf_2.pkl"), geometry="geometry")

In [12]:
gdf_centroids_polygons

,city_name,centroid,geometry,graph_2026,graph_2020
0,"Beijing, China",POINT (116.41898390046961 40.17826035972572),"POLYGON ((116.65389 40.1792, 116.65285 40.1615...","(36380695, 36380698, 36380699, 36380700, 72855...","(36380695, 36380700, 72855718, 72855723, 72855..."
1,"Chengdu, China",POINT (103.9299131329643 30.653447458925932),"POLYGON ((104.13863 30.655, 104.13778 30.6373,...","(276556859, 276556860, 276556885, 276556900, 2...","(276556799, 276556900, 276556908, 276557064, 2..."
2,"Chongqing, China",POINT (107.8658844454987 30.05462134902427),"POLYGON ((108.07308 30.04994, 108.07154 30.032...","(4663024480, 4663024482, 4663024492, 466302449...","(5510660710, 6201942791, 6201942804, 620194280..."
3,"Guangzhou, China",POINT (113.53992658306854 23.327760364828965),"POLYGON ((113.73535 23.32447, 113.73405 23.306...","(370231276, 370231305, 370231438, 445778214, 4...","(370231276, 370231305, 370231438, 445778214, 4..."
4,"Hangzhou, China",POINT (119.4686666897235 29.900427525160346),"POLYGON ((119.67561 29.89639, 119.67414 29.878...","(672831391, 672831767, 672831850, 672831851, 6...","(672831391, 672831511, 672831588, 672831767, 6..."
5,"Shanghai, China",POINT (121.84949810718098 31.245960612803987),"POLYGON ((122.0595 31.24767, 122.05867 31.2299...","(77997015, 77997031, 77998471, 77998473, 77999...","(77998471, 77998473, 77999142, 77999143, 77999..."
6,"Shenzhen, China",POINT (114.5791688697219 22.500548831919602),"POLYGON ((114.77346 22.50335, 114.77281 22.485...","(653128103, 653128189, 670742698, 685056597, 6...","(653127753, 653128103, 653128189, 670742698, 6..."
7,"Wuhan, China",POINT (114.34247757358415 30.622391630613123),"POLYGON ((114.55095 30.62649, 114.5504 30.6087...","(267620065, 286073041, 286073322, 286073497, 2...","(267620078, 286073041, 286073313, 286073322, 2..."
8,"Nanjing, China",POINT (118.84308111020037 31.926202065248283),"POLYGON ((119.05453 31.92296, 119.05311 31.905...","(29571639, 29571641, 304815373, 304815377, 304...","(29571632, 29571641, 29571710, 32918369, 30481..."
9,"Taipei, Taiwan",POINT (120.67220079121316 23.50888347070445),"POLYGON ((120.86767 23.50415, 120.86621 23.486...","(59943316, 59943336, 59943358, 59943393, 59943...","(59943316, 59943336, 59943358, 59943393, 59943..."
10,"Osaka, Japan",POINT (135.4694198247876 34.66243145195363),"POLYGON ((135.68769 34.6614, 135.68649 34.6437...","(241792851, 241792852, 241792853, 241792873, 2...","(241792851, 241792852, 241792853, 241792873, 2..."
11,"Seoul, South Korea",POINT (126.99177598275283 37.551899148604086),"POLYGON ((127.21808 37.55553, 127.21741 37.537...",None,None
12,"Bangkok, Thailand",POINT (100.61532273376511 13.755100628034494),"POLYGON ((100.80025 13.75382, 100.79922 13.736...",None,None
13,"Delhi, India",POINT (77.14824147823546 28.576469149337317),"POLYGON ((77.35259 28.57308, 77.35121 28.55542...",None,None
14,"Singapore, Singapore",POINT (103.91161378122291 1.3291122104153084),"POLYGON ((104.09137 1.32919, 104.09051 1.31145...",None,None
15,"Kuala Lumpur, Malaysia",POINT (101.68991729079005 3.1435230215363936),"POLYGON ((101.86971 3.14304, 101.86879 3.12533...",None,None
16,"Hyderabad, India",POINT (78.45473389424762 17.426752721591573),"POLYGON ((78.64289 17.42907, 78.64221 17.41135...",None,None
17,"Kathmandu, Nepal",POINT (85.32731273788731 27.709055443879848),"POLYGON ((85.53011 27.71136, 85.52937 27.69366...",None,None
18,"Melbourne, Australia",POINT (145.2673733912464 -37.851251524368024),"POLYGON ((145.49463 -37.85438, 145.49317 -37.8...",None,None
19,"Sydney, Australia",POINT (150.92083632213814 -33.7663631219269),"POLYGON ((151.1367 -33.76981, 151.13527 -33.78...",None,None
20,"Auckland, New Zealand",POINT (174.8691768137167 -36.52187205569054),"POLYGON ((175.09243 -36.52565, 175.09092 -36.5...",None,None
21,"Brisbane, Australia",POINT (152.97148739092023 -27.43755484237719),"POLYGON ((153.17386 -27.43745, 153.17291 -27.4...",None,None
22,"Cairo, Egypt",POINT (31.601415169265575 29.98384992348242),"POLYGON ((31.8087 29.98589, 31.80791 29.96819,...",None,None
23,"Casablanca, Morocco",POINT (-7.600544387399278 33.56670144049522),"POLYGON ((-7.38514 33.56408, -7.3865 33.54642,...",None,None
24,"Lagos, Nigeria",POINT (3.5957055565414353 6.52037006962666),"POLYGON ((3.77659 6.52012, 3.77569 6.50239, 3....",None,None
25,"Nairobi, Kenya",POINT (36.86686811220128 -1.2930552439785734),"POLYGON ((37.04653 -1.2932, 37.04565 -1.31093,...",None,None
26,"Amsterdam, Netherlands",POINT (4.904553716037124 52.37343844514592),"POLYGON ((5.19813 52.36834, 5.19584 52.35076, ...",None,None
27,"Brussels, Belgium",POINT (4.3752324031210605 50.87296129908321),"POLYGON ((4.65937 50.86927, 4.65738 50.85167, ...",None,None
28,"London, United Kingdom",POINT (-0.1093106146451765 51.500501049100194),"POLYGON ((0.1784 51.49305, 0.17579 51.47549, 0...",None,None
29,"Paris, France",POINT (2.342885883526181 48.85662615578561),"POLYGON ((2.61553 48.85786, 2.61436 48.84022, ...",None,None
30,"Berlin, Germany",POINT (13.402419248750519 52.501489918453224),"POLYGON ((13.69697 52.5051, 13.69607 52.48747,...",None,None
31,"Munich, Germany",POINT (11.54740658693952 48.15316186830676),"POLYGON ((11.816 48.14689, 11.81375 48.12931, ...",None,None
32,"Madrid, Spain",POINT (-3.696369345662459 40.4653974063716),"POLYGON ((-3.46047 40.46658, -3.46148 40.44891...",None,None
33,"Milan, Italy",POINT (9.17302521447392 45.468387447000936),"POLYGON ((9.42887 45.46771, 9.42751 45.45007, ...",None,None
34,"Moscow, Russia",POINT (37.36179340268065 55.5584204651225),"POLYGON ((37.67878 55.56225, 37.67784 55.54462...",None,None
35,"Stockholm, Sweden",POINT (17.99707102817412 59.32200179109557),"POLYGON ((18.34789 59.31345, 18.34447 59.29592...",None,None
36,"Bucharest, Romania",POINT (26.08778796479756 44.44144121940777),"POLYGON ((26.3391 44.44317, 26.33809 44.42552,...",None,None
37,"Saint Petersburg, Russia",POINT (30.06964962570451 59.962396397238614),"POLYGON ((30.42744 59.96986, 30.42708 59.95224...",None,None
38,"New York City, USA",POINT (-73.93908903040628 40.66319284502448),"POLYGON ((-73.70254 40.66078, -73.70402 40.643...",None,None
39,"Los Angeles, USA",POINT (-118.4070328588624 34.08932219110176),"POLYGON ((-118.19029 34.09161, -118.19108 34.0...",None,None
40,"Detroit, USA",POINT (-83.102158892894 42.383417791401186),"POLYGON ((-82.85934 42.38761, -82.85999 42.369...",None,None
41,"Philadelphia, USA",POINT (-75.13417050258728 40.00757451213557),"POLYGON ((-74.89984 40.00761, -74.901 39.98995...",None,None
42,"San Antonio, USA",POINT (-98.52367236449568 29.464522065691117),"POLYGON ((-98.31742 29.46362, -98.31853 29.445...",None,None
43,"San Diego, USA",POINT (-117.13346400593568 32.816703719197065),"POLYGON ((-116.91981 32.81675, -116.92085 32.7...",None,None
44,"Toronto, Canada",POINT (-79.38853438006605 43.722803905081896),"POLYGON ((-79.14035 43.71903, -79.14209 43.701...",None,None
45,"Montreal, Canada",POINT (-73.65020428992253 45.526648906474044),"POLYGON ((-73.39418 45.52334, -73.39592 45.505...",None,None
46,"Chicago, USA",POINT (-87.68551063998328 41.83804155677118),"POLYGON ((-87.44464 41.83923, -87.44567 41.821...",None,None
47,"Houston, USA",POINT (-95.37605041000089 29.776544107175283),"POLYGON ((-95.16931 29.7801, -95.16992 29.7624...",None,None
48,"Phoenix, USA",POINT (-112.08921983406609 33.571772809392044),"POLYGON ((-111.87375 33.57348, -111.87461 33.5...",None,None
49,"Lima, Peru",POINT (-77.04892854455689 -12.051028047011657),"POLYGON ((-76.86528 -12.05232, -76.86628 -12.0...",None,None
50,"Bogota, Colombia",POINT (-74.10667990375046 4.654203504105394),"POLYGON ((-73.92638 4.65395, -73.92728 4.63622...",None,None
51,"Sao Paulo, Brazil",POINT (-46.648293078843786 -23.650346654011),"POLYGON ((-46.45225 -23.65231, -46.45339 -23.6...",None,None
52,"Caracas, Venezuela",POINT (-66.89318875249243 10.456754482176168),"POLYGON ((-66.71057 10.4555, -66.71158 10.4377...",None,None
53,"Brasilia, Brazil",POINT (-53.08780755059959 -10.56996504472314),"POLYGON ((-52.9051 -10.57112, -52.90609 -10.58...",None,None
54,"Asuncion, Paraguay",POINT (-57.60249998075223 -25.288454990061727),"POLYGON ((-57.40384 -25.28913, -57.40486 -25.3...",None,None

In [4]:
gdf = gdf_centroids_polygons.dropna(subset="graph_2026")

In [5]:
gdf

,city_name,centroid,geometry,graph_2026,graph_2020
0,"Beijing, China",POINT (116.41898390046961 40.17826035972572),"POLYGON ((116.65389 40.1792, 116.65285 40.1615...","(36380695, 36380698, 36380699, 36380700, 72855...","(36380695, 36380700, 72855718, 72855723, 72855..."
1,"Chengdu, China",POINT (103.9299131329643 30.653447458925932),"POLYGON ((104.13863 30.655, 104.13778 30.6373,...","(276556859, 276556860, 276556885, 276556900, 2...","(276556799, 276556900, 276556908, 276557064, 2..."
2,"Chongqing, China",POINT (107.8658844454987 30.05462134902427),"POLYGON ((108.07308 30.04994, 108.07154 30.032...","(4663024480, 4663024482, 4663024492, 466302449...","(5510660710, 6201942791, 6201942804, 620194280..."
3,"Guangzhou, China",POINT (113.53992658306854 23.327760364828965),"POLYGON ((113.73535 23.32447, 113.73405 23.306...","(370231276, 370231305, 370231438, 445778214, 4...","(370231276, 370231305, 370231438, 445778214, 4..."
4,"Hangzhou, China",POINT (119.4686666897235 29.900427525160346),"POLYGON ((119.67561 29.89639, 119.67414 29.878...","(672831391, 672831767, 672831850, 672831851, 6...","(672831391, 672831511, 672831588, 672831767, 6..."
5,"Shanghai, China",POINT (121.84949810718098 31.245960612803987),"POLYGON ((122.0595 31.24767, 122.05867 31.2299...","(77997015, 77997031, 77998471, 77998473, 77999...","(77998471, 77998473, 77999142, 77999143, 77999..."
6,"Shenzhen, China",POINT (114.5791688697219 22.500548831919602),"POLYGON ((114.77346 22.50335, 114.77281 22.485...","(653128103, 653128189, 670742698, 685056597, 6...","(653127753, 653128103, 653128189, 670742698, 6..."
7,"Wuhan, China",POINT (114.34247757358415 30.622391630613123),"POLYGON ((114.55095 30.62649, 114.5504 30.6087...","(267620065, 286073041, 286073322, 286073497, 2...","(267620078, 286073041, 286073313, 286073322, 2..."
8,"Nanjing, China",POINT (118.84308111020037 31.926202065248283),"POLYGON ((119.05453 31.92296, 119.05311 31.905...","(29571639, 29571641, 304815373, 304815377, 304...","(29571632, 29571641, 29571710, 32918369, 30481..."
9,"Taipei, Taiwan",POINT (120.67220079121316 23.50888347070445),"POLYGON ((120.86767 23.50415, 120.86621 23.486...","(59943316, 59943336, 59943358, 59943393, 59943...","(59943316, 59943336, 59943358, 59943393, 59943..."
10,"Osaka, Japan",POINT (135.4694198247876 34.66243145195363),"POLYGON ((135.68769 34.6614, 135.68649 34.6437...","(241792851, 241792852, 241792853, 241792873, 2...","(241792851, 241792852, 241792853, 241792873, 2..."
11,"Seoul, South Korea",POINT (126.99177598275283 37.551899148604086),"POLYGON ((127.21808 37.55553, 127.21741 37.537...","(278159482, 282723724, 282723780, 282723804, 2...","(266813237, 278159482, 278159676, 282723724, 2..."
12,"Bangkok, Thailand",POINT (100.61532273376511 13.755100628034494),"POLYGON ((100.80025 13.75382, 100.79922 13.736...","(51479828, 51479831, 51479856, 61703336, 61703...","(51479828, 51479831, 51479856, 51480490, 61703..."
13,"Delhi, India",POINT (77.14824147823546 28.576469149337317),"POLYGON ((77.35259 28.57308, 77.35121 28.55542...","(58056528, 60890393, 175610054, 245765478, 246...","(58047704, 58047707, 58049717, 58049718, 58049..."
14,"Singapore, Singapore",POINT (103.91161378122291 1.3291122104153084),"POLYGON ((104.09137 1.32919, 104.09051 1.31145...","(25451915, 25451918, 25451929, 25455287, 25455...","(25451915, 25451918, 25451929, 25455287, 25455..."
15,"Kuala Lumpur, Malaysia",POINT (101.68991729079005 3.1435230215363936),"POLYGON ((101.86971 3.14304, 101.86879 3.12533...","(28918006, 28918012, 28930674, 28930700, 28930...","(28918006, 28918008, 28918012, 28918039, 28930..."
16,"Hyderabad, India",POINT (78.45473389424762 17.426752721591573),"POLYGON ((78.64289 17.42907, 78.64221 17.41135...","(245640546, 245640607, 245640612, 245640721, 2...","(245640546, 245640568, 245640570, 245640576, 2..."
17,"Kathmandu, Nepal",POINT (85.32731273788731 27.709055443879848),"POLYGON ((85.53011 27.71136, 85.52937 27.69366...","(31019057, 31019141, 31019147, 31019262, 31019...","(31019057, 31019074, 31019141, 31019147, 31019..."
18,"Melbourne, Australia",POINT (145.2673733912464 -37.851251524368024),"POLYGON ((145.49463 -37.85438, 145.49317 -37.8...","(579260, 579265, 579267, 579268, 579269, 57927...","(579260, 579261, 579265, 579267, 579268, 57926..."
19,"Sydney, Australia",POINT (150.92083632213814 -33.7663631219269),"POLYGON ((151.1367 -33.76981, 151.13527 -33.78...","(12218599, 12219321, 12224268, 12224270, 12224...","(12218525, 12218598, 12218599, 12218606, 12218..."
20,"Auckland, New Zealand",POINT (174.8691768137167 -36.52187205569054),"POLYGON ((175.09243 -36.52565, 175.09092 -36.5...","(716253, 716265, 716439, 716505, 716521, 25149...","(716253, 716265, 716439, 716442, 716505, 71650..."

# classify

In [ ]:
import sys
sys.path.insert(0, './street-pattern-classifier')
from huggingface_hub import hf_hub_download
import torch
from splits import split_graph
from block_dataset import BlockDataset
from classification import classify_blocks
from collections import Counter
from model import class_names


model_path = hf_hub_download(
        repo_id="nochka/street-pattern-classifier",
        filename="best_model.pth",
        local_dir="./models"
)
def classify_city(G, model_path):
    # subgraphs = split_graph(G, resolution=50)
    subgraphs = split_graph(G, grid_step=1000)
    dataset = BlockDataset(subgraphs)
    predictions_blocks, probabilities_blocks = classify_blocks(
        dataset,
        model_path=model_path,
        device='cpu'
    )
    predictions_list = list(predictions_blocks.values())
    class_counts = Counter(predictions_list)
    most_common_class = class_counts.most_common(1)[0][0]

    

    return class_names[most_common_class]

In [5]:
import sys
sys.path.insert(0, './street-pattern-classifier')
from huggingface_hub import hf_hub_download
import torch
from splits import split_graph
from block_dataset import BlockDataset
from classification import classify_blocks
from collections import Counter
from model import class_names
import geopandas as gpd
import pandas as pd
from shapely.geometry import Polygon
from tqdm import tqdm

model_path = hf_hub_download(
    repo_id="nochka/street-pattern-classifier",
    filename="best_model.pth",
    local_dir="./models"
)

def classify_city(G, model_path, year=None):

    subgraphs = split_graph(G, grid_step=1000)
    dataset = BlockDataset(subgraphs)
    predictions_blocks, probabilities_blocks = classify_blocks(
        dataset,
        model_path=model_path,
        device='cpu'
    )
    
    # predictions_blocks - словарь {cell_id: predicted_class}
    # probabilities_blocks - словарь {cell_id: probabilities_array}
    
    # Создаем список для хранения данных
    data = []
    
    # Проходим по всем блокам в subgraphs
    for cell_id, cell_data in subgraphs.items():
        if cell_id in predictions_blocks:
            predicted_class = predictions_blocks[cell_id]
            probabilities = probabilities_blocks[cell_id]
            
            # Создаем словарь с вероятностями для каждого класса
            probs_dict = {}
            for idx, prob in enumerate(probabilities):
                class_name = class_names[idx] if idx < len(class_names) else f"class_{idx}"
                probs_dict[class_name] = prob
            
            # Добавляем данные
            data.append({
                'subgraph': cell_data['graph'],
                'polygon': cell_data['polygon'],
                'predicted_class': class_names[predicted_class] if predicted_class < len(class_names) else predicted_class,
                'predicted_class_id': predicted_class,
                'probabilities': probs_dict,
                'year': year
            })
    
    # Создаем GeoDataFrame
    gdf_results = gpd.GeoDataFrame(data, geometry='polygon', crs=G.graph.get('crs', 'EPSG:4326'))
    
    # Добавляем отдельные колонки для вероятностей каждого класса
    for class_name in class_names:
        gdf_results[f'prob_{class_name}'] = gdf_results['probabilities'].apply(lambda x: x.get(class_name, 0))
    
    return gdf_results

d:\выбирай итмо и не  выбирай вообще\urban\corr_transport_street_pattern\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
gdf_classes = gdf.copy()["city_name"]

In [8]:
gdf_classes

0             Beijing, China
1             Chengdu, China
2           Chongqing, China
3           Guangzhou, China
4            Hangzhou, China
5            Shanghai, China
6            Shenzhen, China
7               Wuhan, China
8             Nanjing, China
9             Taipei, Taiwan
10              Osaka, Japan
11        Seoul, South Korea
12         Bangkok, Thailand
13              Delhi, India
14      Singapore, Singapore
15    Kuala Lumpur, Malaysia
16          Hyderabad, India
17          Kathmandu, Nepal
18      Melbourne, Australia
19         Sydney, Australia
20     Auckland, New Zealand
Name: city_name, dtype: object

In [29]:
gdf_classes = gdf.copy(["city_name"])
gdf_classes["class_2020"] = None
gdf_classes["class_2026"] = None

for i in tqdm(range(len(gdf))):
    curr_row = gdf.iloc[i]
    graph_2026 = ox.project_graph(curr_row["graph_2026"])
    graph_2020 = ox.project_graph(curr_row["graph_2020"])


    class_2026 = classify_city(graph_2026, model_path)
    class_2020 = classify_city(graph_2020, model_path)

    gdf_classes.at[curr_row.name, 'class_2026'] = class_2026
    gdf_classes.at[curr_row.name, 'class_2020'] = class_2020

    print()
    print()
    print(f"city: {curr_row['city_name']} 2020: {class_2020} 2026: {class_2026}")
    print()
    print()

Assigning nodes to cells: 100%|██████████| 19084/19084 [00:00<00:00, 22191.04it/s]
Assigning edges to cells: 100%|██████████| 46008/46008 [00:08<00:00, 5150.33it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1139/1139 [03:45<00:00,  5.05it/s]

Normalization...
Number of nodes: 18066
Number of features: 8
Подготовлено 1139 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 36/36 [00:03<00:00,  9.80it/s]
Assigning nodes to cells: 100%|██████████| 12549/12549 [00:00<00:00, 17520.02it/s]
Assigning edges to cells: 100%|██████████| 31572/31572 [00:06<00:00, 4679.24it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1071/1071 [03:04<00:00,  5.80it/s]

Normalization...
Number of nodes: 13715
Number of features: 8
Подготовлено 1071 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 34/34 [00:03<00:00, 10.43it/s]
  9%|▉         | 1/11 [07:19<1:13:16, 439.62s/it]

city: Beijing, China 2020: Regular Grid 2026: Irregular Grid

Assigning nodes to cells: 100%|██████████| 30071/30071 [00:01<00:00, 20970.44it/s]
Assigning edges to cells: 100%|██████████| 70934/70934 [00:18<00:00, 3780.72it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1303/1303 [07:48<00:00,  2.78it/s]

Normalization...
Number of nodes: 34823
Number of features: 8
Подготовлено 1303 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 41/41 [00:07<00:00,  5.67it/s]
Assigning nodes to cells: 100%|██████████| 27826/27826 [00:01<00:00, 17048.10it/s]
Assigning edges to cells: 100%|██████████| 69816/69816 [00:16<00:00, 4154.11it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1260/1260 [10:36<00:00,  1.98it/s]

Normalization...
Number of nodes: 28987
Number of features: 8
Подготовлено 1260 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 40/40 [00:06<00:00,  5.89it/s]
 18%|█▊        | 2/11 [26:47<2:10:09, 867.73s/it]

city: Chengdu, China 2020: Warped Parallel 2026: Irregular Grid

Assigning nodes to cells: 100%|██████████| 674/674 [00:00<00:00, 16357.08it/s]
Assigning edges to cells: 100%|██████████| 1490/1490 [00:00<00:00, 2526.07it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 293/293 [00:22<00:00, 12.76it/s]

Normalization...
Number of nodes: 978
Number of features: 8
Подготовлено 293 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 10/10 [00:00<00:00, 23.05it/s]
Assigning nodes to cells: 100%|██████████| 104/104 [00:00<00:00, 12999.39it/s]
Assigning edges to cells: 100%|██████████| 226/226 [00:00<00:00, 1453.84it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 137/137 [00:06<00:00, 21.57it/s]

Normalization...
Number of nodes: 444
Number of features: 8
Подготовлено 137 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 5/5 [00:00<00:00, 25.36it/s]
 27%|██▋       | 3/11 [27:18<1:04:46, 485.85s/it]

city: Chongqing, China 2020: Warped Parallel 2026: Loops & Lollipops

Assigning nodes to cells: 100%|██████████| 9446/9446 [00:00<00:00, 16357.86it/s]
Assigning edges to cells: 100%|██████████| 20166/20166 [00:05<00:00, 3479.44it/s]

Computing features for all subgraphs...

Processing subgraphs...:  28%|██▊       | 309/1094 [00:50<02:08,  6.10it/s]
 27%|██▋       | 3/11 [28:18<1:15:28, 566.05s/it]

KeyboardInterrupt:

In [10]:
import pickle
import os
from tqdm import tqdm
import pandas as pd
import geopandas as gpd

# Параметры
FORCE_RERUN = False  # Установите True, если хотите перезаписать существующие файлы
os.makedirs("city_results", exist_ok=True)

# Основной цикл обработки
gdf_classes = gdf.copy(["city_name"])
gdf_classes["class_2020"] = None
gdf_classes["class_2026"] = None

all_results = []

# Загружаем список обработанных городов, если не принудительный запуск
processed_cities = set()
if not FORCE_RERUN:
    processed_file = "city_results/processed_cities.txt"
    if os.path.exists(processed_file):
        with open(processed_file, 'r') as f:
            processed_cities = set(f.read().splitlines())

for i in tqdm(range(len(gdf)), desc="Processing cities"):
    curr_row = gdf.iloc[i]
    if "Taipei, Taiwan" in curr_row.city_name:
        continue
    if "Osaka, Japan" in curr_row.city_name:
        continue
    if "Seoul, South Korea" in curr_row.city_name:
        continue
    
    safe_city_name = "".join(c for c in curr_row['city_name'] if c.isalnum() or c in (' ', '-', '_')).rstrip()
    base_filename = f"city_{safe_city_name}_{curr_row.name}"
    blocks_file = f"city_results/{base_filename}_blocks.pkl"
    city_info_file = f"city_results/{base_filename}_city_info.pkl"
    
    # Проверяем, нужно ли пропустить
    if not FORCE_RERUN:
        if os.path.exists(blocks_file) and os.path.exists(city_info_file):
            print(f"Skipping {curr_row['city_name']} - files already exist")
            # Восстанавливаем данные из существующих файлов для summary
            # try:
            #     # Пытаемся загрузить существующие данные для обновления сводки
            #     existing_blocks = pd.read_pickle(blocks_file)
            #     if 'predicted_class' in existing_blocks.columns:
            #         most_common_2020 = existing_blocks[existing_blocks['year'] == 2020]['predicted_class'].mode()[0] if 2020 in existing_blocks['year'].values else None
            #         most_common_2026 = existing_blocks[existing_blocks['year'] == 2026]['predicted_class'].mode()[0] if 2026 in existing_blocks['year'].values else None
            #         if most_common_2020 and most_common_2026:
            #             gdf_classes.at[curr_row.name, 'class_2026'] = most_common_2026
            #             gdf_classes.at[curr_row.name, 'class_2020'] = most_common_2020
            # except:
            #     pass
            continue
        
        if str(curr_row.name) in processed_cities:
            print(f"Skipping {curr_row['city_name']} - already in processed list")
            continue
    
    try:
        print(f"Processing {curr_row['city_name']}...")
        
        # Проектируем графы
        graph_2026 = ox.project_graph(curr_row["graph_2026"])
        graph_2020 = ox.project_graph(curr_row["graph_2020"])
        
        # Классифицируем для каждого года
        gdf_2026 = classify_city(graph_2026, model_path, year=2026)
        gdf_2020 = classify_city(graph_2020, model_path, year=2020)
        
        # Добавляем информацию о городе
        gdf_2026['city_name'] = curr_row['city_name']
        gdf_2020['city_name'] = curr_row['city_name']
        
        all_results.append(gdf_2026)
        all_results.append(gdf_2020)
        
        # Получаем самый популярный класс
        most_common_2026 = gdf_2026['predicted_class'].mode()[0]
        most_common_2020 = gdf_2020['predicted_class'].mode()[0]
        
        gdf_classes.at[curr_row.name, 'class_2026'] = most_common_2026
        gdf_classes.at[curr_row.name, 'class_2020'] = most_common_2020
        
        print(f"  city: {curr_row['city_name']} 2020: {most_common_2020} 2026: {most_common_2026}")
        print(f"  - Blocks 2020: {len(gdf_2020)}")
        print(f"  - Blocks 2026: {len(gdf_2026)}")
        
        # Сохраняем файлы
        combined_city_gdf = pd.concat([gdf_2020, gdf_2026], ignore_index=True)
        combined_city_gdf.to_pickle(blocks_file)
        
        if hasattr(curr_row, 'geometry') and curr_row.geometry is not None:
            curr_row_gdf = gpd.GeoDataFrame([curr_row], crs=gdf.crs)
        else:
            curr_row_gdf = pd.DataFrame([curr_row])
        
        curr_row_gdf.to_pickle(city_info_file)
        
        print(f"  ✓ Saved to {blocks_file} and {city_info_file}")
        
        # Записываем в список обработанных
        with open("city_results/processed_cities.txt", 'a') as f:
            f.write(f"{curr_row.name}\n")
            
    except Exception as e:
        print(f"Error processing city {curr_row['city_name']}: {e}")
        import traceback
        traceback.print_exc()
        continue

# # Сохраняем общие результаты
# if all_results:
#     combined_gdf = pd.concat(all_results, ignore_index=True)
#     combined_gdf.to_pickle("city_results/all_cities_blocks.pkl")
#     gdf_classes.to_pickle("city_results/city_summary.pkl")
#     gdf_classes.to_csv("city_results/city_summary.csv", index=False)
#     print(f"\n✓ Saved summary files to city_results/")
#     print(f"  Total blocks processed: {len(combined_gdf)}")
#     print(f"  Total cities processed: {len(gdf_classes[gdf_classes['class_2020'].notna()])}")
# else:
#     print("No new results were generated")

Processing cities:   0%|          | 0/21 [00:00<?, ?it/s]

Skipping Beijing, China - files already exist
Skipping Chengdu, China - files already exist
Skipping Chongqing, China - files already exist
Skipping Guangzhou, China - files already exist
Skipping Hangzhou, China - files already exist
Skipping Shanghai, China - files already exist
Skipping Shenzhen, China - files already exist
Skipping Wuhan, China - files already exist
Skipping Nanjing, China - files already exist
Processing Bangkok, Thailand...

Assigning nodes to cells: 100%|██████████| 168715/168715 [00:07<00:00, 23171.56it/s]
Assigning edges to cells: 100%|██████████| 363988/363988 [01:10<00:00, 5153.74it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1280/1280 [37:13<00:00,  1.74s/it]

Normalization...
Number of nodes: 52443
Number of features: 8
Подготовлено 1280 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 40/40 [00:09<00:00,  4.12it/s]
Assigning nodes to cells: 100%|██████████| 185811/185811 [00:07<00:00, 23291.22it/s]
Assigning edges to cells: 100%|██████████| 416504/416504 [01:07<00:00, 6197.83it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1298/1298 [53:16<00:00,  2.46s/it]

Normalization...
Number of nodes: 67809
Number of features: 8
Подготовлено 1298 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 41/41 [01:02<00:00,  1.52s/it]

  city: Bangkok, Thailand 2020: Irregular Grid 2026: Irregular Grid
  - Blocks 2020: 1298
  - Blocks 2026: 1280

Processing cities:  62%|██████▏   | 13/21 [1:36:07<59:09, 443.63s/it]

  ✓ Saved to city_results/city_Bangkok Thailand_12_blocks.pkl and city_results/city_Bangkok Thailand_12_city_info.pkl
Processing Delhi, India...

Assigning nodes to cells: 100%|██████████| 177850/177850 [00:08<00:00, 22099.61it/s]
Assigning edges to cells: 100%|██████████| 478954/478954 [01:14<00:00, 6437.72it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1246/1246 [2:12:19<00:00,  6.37s/it]

Normalization...
Number of nodes: 101017
Number of features: 8
Подготовлено 1246 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 39/39 [00:16<00:00,  2.30it/s]
Assigning nodes to cells: 100%|██████████| 162131/162131 [00:07<00:00, 22836.17it/s]
Assigning edges to cells: 100%|██████████| 434028/434028 [01:07<00:00, 6399.19it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1288/1288 [1:31:23<00:00,  4.26s/it]

Normalization...
Number of nodes: 93657
Number of features: 8
Подготовлено 1288 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 41/41 [00:15<00:00,  2.68it/s]

  city: Delhi, India 2020: Irregular Grid 2026: Irregular Grid
  - Blocks 2020: 1288
  - Blocks 2026: 1246

Processing cities:  67%|██████▋   | 14/21 [5:26:02<3:25:59, 1765.61s/it]

  ✓ Saved to city_results/city_Delhi India_13_blocks.pkl and city_results/city_Delhi India_13_city_info.pkl
Processing Singapore, Singapore...

Assigning nodes to cells: 100%|██████████| 21092/21092 [00:00<00:00, 23606.09it/s]
Assigning edges to cells: 100%|██████████| 40092/40092 [00:06<00:00, 6052.57it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 453/453 [04:38<00:00,  1.63it/s]

Normalization...
Number of nodes: 16982
Number of features: 8
Подготовлено 453 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 15/15 [00:03<00:00,  4.78it/s]
Assigning nodes to cells: 100%|██████████| 91260/91260 [00:03<00:00, 23813.00it/s]
Assigning edges to cells: 100%|██████████| 208769/208769 [00:34<00:00, 6086.39it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 536/536 [1:07:01<00:00,  7.50s/it]

Normalization...
Number of nodes: 53169
Number of features: 8
Подготовлено 536 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 17/17 [00:09<00:00,  1.72it/s]

  city: Singapore, Singapore 2020: Irregular Grid 2026: Irregular Grid
  - Blocks 2020: 536
  - Blocks 2026: 453

Processing cities:  71%|███████▏  | 15/21 [6:40:42<3:30:11, 2101.94s/it]

  ✓ Saved to city_results/city_Singapore Singapore_14_blocks.pkl and city_results/city_Singapore Singapore_14_city_info.pkl
Processing Kuala Lumpur, Malaysia...

Assigning nodes to cells: 100%|██████████| 74370/74370 [00:03<00:00, 20280.92it/s]
Assigning edges to cells: 100%|██████████| 166605/166605 [02:08<00:00, 1297.42it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1044/1044 [20:20<00:00,  1.17s/it]

Normalization...
Number of nodes: 46565
Number of features: 8
Подготовлено 1044 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 33/33 [00:08<00:00,  3.78it/s]
Assigning nodes to cells: 100%|██████████| 166277/166277 [00:08<00:00, 20731.50it/s]
Assigning edges to cells: 100%|██████████| 407657/407657 [01:06<00:00, 6128.29it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1143/1143 [1:29:54<00:00,  4.72s/it]

Normalization...
Number of nodes: 89177
Number of features: 8
Подготовлено 1143 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 36/36 [00:14<00:00,  2.48it/s]

  city: Kuala Lumpur, Malaysia 2020: Irregular Grid 2026: Irregular Grid
  - Blocks 2020: 1143
  - Blocks 2026: 1044

Processing cities:  76%|███████▌  | 16/21 [8:35:48<3:55:21, 2824.37s/it]

  ✓ Saved to city_results/city_Kuala Lumpur Malaysia_15_blocks.pkl and city_results/city_Kuala Lumpur Malaysia_15_city_info.pkl
Processing Hyderabad, India...

Assigning nodes to cells: 100%|██████████| 209020/209020 [00:10<00:00, 19530.85it/s]
Assigning edges to cells: 100%|██████████| 543518/543518 [03:24<00:00, 2663.74it/s]

Computing features for all subgraphs...

Processing subgraphs...: 100%|██████████| 1240/1240 [2:18:53<00:00,  6.72s/it]

Normalization...
Number of nodes: 95514
Number of features: 8
Подготовлено 1240 блоков с корректными признаками
Модель загружена

Processing batches: 100%|██████████| 39/39 [00:19<00:00,  1.99it/s]
Assigning nodes to cells: 100%|██████████| 202163/202163 [00:10<00:00, 20007.15it/s]
Assigning edges to cells: 100%|██████████| 544254/544254 [01:37<00:00, 5587.69it/s]

Computing features for all subgraphs...

Processing subgraphs...:  69%|██████▉   | 872/1266 [1:28:37<40:02,  6.10s/it]
Processing cities:  76%|███████▌  | 16/21 [12:32:23<3:55:07, 2821.45s/it]

KeyboardInterrupt: